### PR TITLE
:sparkles: add function to add comment to a Jira ticket

### PR DESCRIPTION
**Pull request by sickler-alex**
# Pull Request Name

- [X] supports https://d3b.atlassian.net/browse/D3B-595
- [X] README entry added if new functionality
- [ ] fixup commits are appropriately squashed

[Description here]

This PR adds a function to add a comment to a Jira ticket. This will be used within the data transfer step function so that each step of the step function can add a comment that the step has finished. I added this here because most if not all of the lambdas in the step function are already importing the cli. I didn't add an option to call this function from the cli because I don't think we need it yet.

### CODE REVIEW

**Review by HuangXiaoyan0106 — APPROVED** [review]

**Review by nicholasvk — CHANGES_REQUESTED** [review]
I think we need a more detailed README about functionality and reason for the jira functions like we did in the notification repo. 

I think we should add an adr here to explain why we are deciding to add the Jira notification functionality here and why we split up our Jira functions for status updates (that reside in the notification lambda repo) and the functions we are adding here. I think we should also add into that ADR the reason/decision we are not adding cli functionality at this point. I am not convinced we shouldn't just add it.

**Comment by sickler-alex** [comment]
I added some more detail to the README. I don't think this is the appropriate place to document what is NOT being done in other repos. There's currently no plans to use this functionality from the command line. If and when there are plans, we can make tickets to add this and plan that out in future discussions. Let's add the minimum functionality necessary to get this finished up.

**Comment by nicholasvk** [comment]
> I added some more detail to the README. I don't think this is the appropriate place to document what is NOT being done in other repos. There's currently no plans to use this functionality from the command line. If and when there are plans, we can make tickets to add this and plan that out in future discussions. Let's add the minimum functionality necessary to get this finished up.

I disagree, I think its important context to explain why we have some jira functionality here and in another repo which could easily be linked to. I just want to make sure we are documenting our decision and reasons for moving this piece of the Jira functionality into the cli repo. I think its also important to note why we are deciding not to actually implement cli functionality. I think its important to do this in a way that follows D3b development standards (adr).

**Review by nicholasvk — CHANGES_REQUESTED** [review]
Per my reply in the discussion, I think we need to create an adr to explain context for adding Jira functionality to the cli repo and do this following D3b standards.

**Review by nicholasvk — APPROVED** [review]
Approving, looks good, thanks for adding in the adr this is really helpful. Just wondering long term if we can avoid the duplication of code by using the cli in the notification lambda down the road?

**Comment by sickler-alex** [comment]
> Approving, looks good, thanks for adding in the adr this is really helpful. Just wondering long term if we can avoid the duplication of code by using the cli in the notification lambda down the road?

OOOH boy, do I have some PRs coming up.

**Pull request closed without merging**
