### PR TITLE
Feature/reorganize dewrangle

### PR DESCRIPTION
**Pull request by sickler-alex**
# Pull Request Name

- [ ] closes #xxxx
- [ ] README entry added if new functionality
- [ ] fixup commits are appropriately squashed

[Description here]

This PR adds functions for checking Dewrangle job status and download results. It also reorganizes the Dewrangle functions to put common functions in a separate file then the ones handling hashing volumes and downloading jobs.

### CODE REVIEW

**Comment by calkinsh** [comment]
is this related to d3b-420?

**Comment by HuangXiaoyan0106** [comment]
@sickler-alex I got this error when I run `d3b dewrangle list_jobs`
```
% d3b dewrangle list_jobs -study sd-86n4tk8ekn -bucket d3b-study-us-east-1-prd-sd-32sc9wns
Vm9sdW1lOmNsc3pxODk4cDAwMDI4c29qN3VtODk2cmc=
Traceback (most recent call last):
  File "/Users/xiaoyan/opt/anaconda3/bin/d3b", line 8, in <module>
    sys.exit(main())
  File "/Users/xiaoyan/opt/anaconda3/lib/python3.8/site-packages/d3b_dff_cli/cli.py", line 149, in main
    args.func(args)
  File "/Users/xiaoyan/opt/anaconda3/lib/python3.8/site-packages/d3b_dff_cli/modules/dewrangle/list_jobs.py", line 70, in main
    list_volume_jobs(
  File "/Users/xiaoyan/opt/anaconda3/lib/python3.8/site-packages/d3b_dff_cli/modules/dewrangle/list_jobs.py", line 28, in list_volume_jobs
    jobs = hf.get_volume_jobs(client, volume_id)
  File "/Users/xiaoyan/opt/anaconda3/lib/python3.8/site-packages/d3b_dff_cli/modules/dewrangle/helper_functions.py", line 385, in get_volume_jobs
    comp = datetime.strptime(
TypeError: strptime() argument 1 must be str, not None
```

**Comment by sickler-alex** [comment]
@HuangXiaoyan0106 try again. It looks like there was a group of jobs running today. I'm not sure what timezone Dewrangle uses. Maybe those jobs were running when you were testing this? The command is working for me now.

**Review by HuangXiaoyan0106 — APPROVED** [review]
It works for me.

**Pull request merged**
